FROM node:22-alpine

WORKDIR /app

COPY package.json ./

COPY yarn.lock ./

RUN yarn install

COPY . .

EXPOSE 5000

CMD ["./node_modules/.bin/nodemon", "--watch", "src", "--exec", "./node_modules/.bin/babel-node", "src/server.js"]